apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2026-09-02T13:33:07Z"
  labels:
    app: hello-server
  name: hello-server
  namespace: default
  uid: a4092840-05d7-496d-9f76-866705a67b71
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - image: ghcr.io/nak0x/tp-lead-teach:staging
        imagePullPolicy: IfNotPresent
        name: images
        args:
        - health
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-09-02T13:33:18Z"
    lastUpdateTime: "2026-09-02T13:33:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-09-02T13:33:07Z"
    lastUpdateTime: "2026-09-02T13:33:18Z"
    message: ReplicaSet "hello-server-66bd54ff48" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  terminatingReplicas: 0
  updatedReplicas: 1
