name: publish-production

on:
  push:
    branches:
      - main

jobs:
  publish-production-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the production Docker image
        run: |
          docker build . --tag ghcr.io/nak0x/tp-lead-teach:production
          docker push ghcr.io/nak0x/tp-lead-teach:production
